# Generated by Django 5.2.11 on 2026-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='dark_bg_color',
            field=models.CharField(default='#1a1a1a', help_text='Dark mode background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='dark_card_bg',
            field=models.CharField(default='#2d2d2d', help_text='Dark mode card background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, help_text='Enable dark mode for the site'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='dark_text_color',
            field=models.CharField(default='#e0e0e0', help_text='Dark mode text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='nav_hover_color',
            field=models.CharField(default='rgba(255,255,255,0.15)', max_length=50),
        ),
    ]
