# Generated by Cursor on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitetheme_dark_bg_color_sitetheme_dark_card_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='show_nav_arrows',
            field=models.BooleanField(default=True, help_text='Show back/forward arrows in the navbar'),
        ),
    ]

