# Generated by Django 5.0.6 on 2026-02-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, K, M', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class e.g. fa-users', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
