# Generated by Django 5.2.11 on 2026-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_date_of_issue_member_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='collaborations/')),
                ('partnership_type', models.CharField(choices=[('mou', 'Memorandum of Understanding (MOU)'), ('academic', 'Academic Partner'), ('ngo', 'NGO Partner'), ('corporate', 'Corporate Partner'), ('government', 'Government Partner'), ('wing', 'Partner Wing'), ('strategic', 'Strategic Partner')], default='mou', max_length=20)),
                ('short_description', models.TextField(help_text='Brief 2-3 line summary', max_length=300)),
                ('full_description', models.TextField(blank=True, help_text='Complete description of collaboration')),
                ('objectives', models.TextField(blank=True, help_text='Objectives and scope of partnership')),
                ('programs_activities', models.TextField(blank=True, help_text='Programs or activities conducted')),
                ('impact_outcomes', models.TextField(blank=True, help_text='Impact and outcomes achieved')),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='active', max_length=20)),
                ('partner_website', models.URLField(blank=True, help_text='Partner organization website')),
                ('partner_contact', models.CharField(blank=True, max_length=200)),
                ('mou_document', models.FileField(blank=True, help_text='Optional downloadable MOU file', null=True, upload_to='collaborations/mous/')),
                ('supporting_images', models.ImageField(blank=True, help_text='Supporting image or photo', null=True, upload_to='collaborations/gallery/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
                'ordering': ['order', '-agreement_date', 'organization_name'],
            },
        ),
    ]
