# Generated by Django 5.2.11 on 2026-02-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='detail_background_color',
            field=models.CharField(blank=True, choices=[('', 'Default (Warm cream)'), ('#faf8f5', 'Cream'), ('#f5f2ed', 'Warm beige'), ('#f0f7f4', 'Mint green'), ('#e8f4f8', 'Soft blue'), ('#f8f4e8', 'Light gold'), ('#f5f0e8', 'Sand'), ('#eef5f0', 'Sage')], help_text='Background color for detail page. Leave blank for default.', max_length=7),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='detail_background_image',
            field=models.ImageField(blank=True, help_text='Optional background image for detail page. Shown with subtle overlay.', null=True, upload_to='collaborations/backgrounds/'),
        ),
    ]
