# Generated by Django 5.2.11 on 2026-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_collaboration_detail_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
    ]
