# Generated by Django 5.2.11 on 2026-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_add_social_media_and_auto_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role_level',
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('board', 'Board Member'), ('volunteer', 'Volunteer')], default='volunteer', help_text='Select Board Member or Volunteer', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated based on member type', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, help_text='Optional role/title (e.g., President, Secretary, etc.)', max_length=200),
        ),
    ]
