# Generated by Cursor on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_simplify_to_board_and_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='Our Team', max_length=200)),
                ('subtitle_template', models.CharField(default='Meet the people behind NHAF Nepal. {count} members dedicated to community health.', help_text='Use {count} where the member count should appear.', max_length=300)),
                ('title_font_family', models.CharField(choices=[('nunito', 'Nunito (friendly)'), ('dm_sans', 'DM Sans (default)'), ('plus_jakarta', 'Plus Jakarta Sans (modern)')], default='nunito', max_length=20)),
                ('subtitle_font_family', models.CharField(choices=[('nunito', 'Nunito (friendly)'), ('dm_sans', 'DM Sans (default)'), ('plus_jakarta', 'Plus Jakarta Sans (modern)')], default='nunito', max_length=20)),
                ('title_font_size_px', models.PositiveIntegerField(default=44, help_text='Title font size in pixels (desktop).')),
                ('subtitle_font_size_px', models.PositiveIntegerField(default=20, help_text='Subtitle font size in pixels (desktop).')),
                ('title_color', models.CharField(default='var(--text-dark)', max_length=20)),
                ('subtitle_color', models.CharField(default='var(--text-muted)', max_length=20)),
                ('heading_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('typing_enabled', models.BooleanField(default=True, help_text='Enable typing animation for title/subtitle.')),
                ('typing_speed_ms', models.PositiveIntegerField(default=90, help_text='Typing speed per character in ms.')),
                ('board_line_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('gradient', 'Gradient')], default='gradient', max_length=20)),
                ('board_line_thickness_px', models.PositiveIntegerField(default=4)),
                ('board_line_color', models.CharField(default='var(--primary)', max_length=20)),
                ('board_line_color_2', models.CharField(default='var(--primary-light)', max_length=20)),
                ('board_line_full_width', models.BooleanField(default=True)),
                ('board_line_length_percent', models.PositiveIntegerField(default=100, help_text='Used when full width is off (10–100).')),
                ('volunteer_line_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('gradient', 'Gradient')], default='gradient', max_length=20)),
                ('volunteer_line_thickness_px', models.PositiveIntegerField(default=4)),
                ('volunteer_line_color', models.CharField(default='var(--primary)', max_length=20)),
                ('volunteer_line_color_2', models.CharField(default='var(--primary-light)', max_length=20)),
                ('volunteer_line_full_width', models.BooleanField(default=True)),
                ('volunteer_line_length_percent', models.PositiveIntegerField(default=100, help_text='Used when full width is off (10–100).')),
                ('show_search', models.BooleanField(default=True, help_text='Show the search box on the Team page.')),
                ('background_watermark', models.ImageField(blank=True, null=True, upload_to='team/backgrounds/')),
                ('watermark_opacity', models.DecimalField(decimal_places=2, default=0.08, help_text='0.00–1.00', max_digits=3)),
                ('watermark_position', models.CharField(choices=[('center', 'Center'), ('top-left', 'Top left'), ('top-right', 'Top right'), ('bottom-left', 'Bottom left'), ('bottom-right', 'Bottom right')], default='center', max_length=20)),
                ('watermark_size_percent', models.PositiveIntegerField(default=55, help_text='Watermark size as % (10–120).')),
                ('card_radius_px', models.PositiveIntegerField(default=18)),
                ('card_min_height_px', models.PositiveIntegerField(default=420)),
                ('card_max_height_px', models.PositiveIntegerField(default=540)),
                ('social_icon_size_px', models.PositiveIntegerField(default=32)),
                ('name_font_size_px', models.PositiveIntegerField(default=22)),
                ('role_font_size_px', models.PositiveIntegerField(default=14)),
                ('id_font_size_px', models.PositiveIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Team page settings',
                'verbose_name_plural': 'Team page settings',
            },
        ),
    ]

