# Generated by Cursor for enhanced Team Page CMS

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_team_page_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampagesettings',
            name='title_animation',
            field=models.CharField(
                choices=[('none', 'None'), ('typing', 'Typing'), ('fade', 'Fade in'), ('slide', 'Slide up'), ('zoom', 'Zoom in'), ('bounce', 'Bounce')],
                default='typing',
                help_text='Animation type for title/subtitle.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='card_hover_effect',
            field=models.CharField(choices=[('none', 'None'), ('lift', 'Lift up'), ('scale', 'Scale up'), ('glow', 'Glow')], default='lift', max_length=20),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='card_shadow',
            field=models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('medium', 'Medium'), ('strong', 'Strong')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='card_animation',
            field=models.CharField(choices=[('none', 'None'), ('fadeIn', 'Fade in'), ('slideUp', 'Slide up'), ('zoomIn', 'Zoom in')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='section_spacing_px',
            field=models.PositiveIntegerField(default=24, help_text='Spacing between sections (px).'),
        ),
        migrations.AddField(
            model_name='teampagesettings',
            name='card_padding_px',
            field=models.PositiveIntegerField(default=16, help_text='Card inner padding (px).'),
        ),
        migrations.AlterField(
            model_name='teampagesettings',
            name='title_color',
            field=models.CharField(default='var(--text-dark)', max_length=50),
        ),
        migrations.AlterField(
            model_name='teampagesettings',
            name='subtitle_color',
            field=models.CharField(default='var(--text-muted)', max_length=50),
        ),
        migrations.AlterField(
            model_name='teampagesettings',
            name='title_font_family',
            field=models.CharField(choices=[('nunito', 'Nunito (friendly)'), ('dm_sans', 'DM Sans (default)'), ('plus_jakarta', 'Plus Jakarta Sans (modern)'), ('inter', 'Inter (clean)'), ('poppins', 'Poppins (rounded)'), ('open_sans', 'Open Sans (readable)'), ('lato', 'Lato (neutral)'), ('roboto', 'Roboto (system-like)'), ('playfair', 'Playfair Display (serif)'), ('merriweather', 'Merriweather (serif)')], default='nunito', max_length=30),
        ),
        migrations.AlterField(
            model_name='teampagesettings',
            name='subtitle_font_family',
            field=models.CharField(choices=[('nunito', 'Nunito (friendly)'), ('dm_sans', 'DM Sans (default)'), ('plus_jakarta', 'Plus Jakarta Sans (modern)'), ('inter', 'Inter (clean)'), ('poppins', 'Poppins (rounded)'), ('open_sans', 'Open Sans (readable)'), ('lato', 'Lato (neutral)'), ('roboto', 'Roboto (system-like)'), ('playfair', 'Playfair Display (serif)'), ('merriweather', 'Merriweather (serif)')], default='nunito', max_length=30),
        ),
    ]
